services:
  app:
    build:
      target: prod
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8020:8000"
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m

  postgres:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
